### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by starlikeleo** [starlikeleo/furima-30944#10]
# URL
https://furima-30944.herokuapp.com/
# Basic認証
ユーザ名：admin　パスワード：2222
# 出品者
メール：furimataro@gmail.com　パスワード：Aa123456
# 購入者
メール：jiro@gmail.com　パスワード：Bb123456
# 購入用カード
番号：4242424242424242　
期限：03月24年　
セキュリティコード：123
# 購入用商品
yadon

**Comment by snkw-works** [comment]
@starlikeleo さん、ご提出ありがとうございます‼︎ 挙動確認お待ちいただきありがとうございます。
動作の確認をしたところ、修正していただきたい箇所がございました。
以下、ご確認をお願いします！

[修正依頼箇所]
- [x] **商品出品画面にて、入力された販売価格によって、販売手数料や販売利益が変わるよう修正しましょう(JavaScriptを使用して実装すること)**
現状、価格を入力しても販売手数料や販売利益が表示されない状態です。

- [x] **商品購入ページでは、一覧や詳細ページで選択した商品の情報が出力されるよう修正しましょう**
現状、価格が正しく表示されていない状態です。
<img width="860" alt="スクリーンショット_2021-04-19_15_17_08" src="https://user-images.githubusercontent.com/54050089/115190588-39c3e980-a123-11eb-906e-24cbfda6b489.png">

- [x] **商品購入時の電話番号にはハイフンは不要で、11桁以内であるよう修正しましょう（09012345678となる）**
現状、ハイフンが入った電話番号でも購入ができる状態です。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by starlikeleo** [comment]
挙動確認有り難うございます！！！
３点修正致しました。

ご査収お願い致します。

**Comment by hidetttttora** [comment]
@starlikeleo さん、再度ご提出ありがとうございます‼︎

修正箇所の動作確認をしたところ、改めまして修正していただきたい箇所がございました。
以下のご確認をお願いします！

## [修正依頼箇所]

- [x] **商品購入ページでは、一覧や詳細ページで選択した商品の情報が出力されるよう修正しましょう**
現状、前回に引き続き価格が正しく表示されていない状態です。
前回は「¥」が表示されていましたが、今回はその表示もない状態です。
「￥30,000」のように、その商品の登録情報の価格を配送料情報の左側へ表示させましょう。
![スクリーンショット 2021-04-20 12 25 32](https://user-images.githubusercontent.com/50098627/115332921-b7473280-a1d3-11eb-8d50-07cdad4e5af0.png)


##
修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by starlikeleo** [comment]
申し訳ありません、うっかり抜けてました！！！
修正致しました。

再確認お願い致します。

**Comment by mo1015** [comment]
ご提出ありがとうございます！
お待たせいたしました。問題なく正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉


**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/62644781/115491820-a104a980-a29b-11eb-90ff-e1fc53411982.png)

**Comment by starlikeleo** [comment]
LGTM有り難うございます！！！
残りのカリキュラムも頑張ります⭐️
